//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteList
    {
        public int Id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public System.DateTime DOB { get; set; }
        public int carYear { get; set; }
        public string carMake { get; set; }
        public string carModel { get; set; }
        public short speedTickets { get; set; }
        public Nullable<bool> DUI { get; set; }
        public Nullable<bool> fullCoverage { get; set; }
        public int completedQuote { get; set; }
    }
}
